file:
  input: ""
  output: ""
settings:
  dictionary: LOOKALIKE_IL
  dependencies:
    - "spigot-1.17.1.jar"
    - "rt.jar"
    - "resources.jar"
    - "jsse.jar"
    - "jce.jar"
    - "charsets.jar"
    - "jfr.jar"
    - "AbyssLib-PRE.jar"
  exclusions:
    - "Global: com/"
    - "Global: edu/"
    - "Global: io/"
    - "Global: javax/"
    - "Global: me/"
    - "Global: nonapi/"
    - "Global: org/"
    - "Global: uk/"
    - "Global: co/"
    - "Global: jdk/"
    - "Global: sun/"
    - "Global: java/"
    - "Global: jdk/"
    - "Global: sun/"
    - "Global: java/"
  inclusions: []
transformers:
  nopspamtransformer:
    enabled: false
  old qprotect string transformer:
    enabled: false
  string call optimizer:
    enabled: false
  anti debugger:
    enabled: false
  resource encryption:
    enabled: true
  field reference encryption:
    enabled: true
  string encryption:
    enabled: true
  enhanced string encryption:
    enabled: true
  flow transformer:
    enabled: true
    settings:
      goto replacer:
        enabled: false
      reverse jumps:
        enabled: true
      lookupswitch replacer:
        enabled: true
      trycatch blocks:
        enabled: true
      useless checkcast:
        enabled: true
      polymorph transformer:
        enabled: true
      tableswitch transformer:
        enabled: true
  reference encryption:
    enabled: false
  number transformer:
    enabled: true
  arithmetic transformer:
    enabled: true
  source transformer:
    enabled: true
  line number transformer:
    enabled: true
    settings: Mutate
  local variable transformer:
    enabled: false
    settings: Mutate
  crasher:
    enabled: false
  shuffle members:
    enabled: false
  access transformer:
    enabled: false
  nop instruction remover:
    enabled: false
  classfolder transformer:
    enabled: false
  inner class remover:
    enabled: false
renamer:
  transformers:
    class renamer:
      enabled: false
    field renamer:
      enabled: false
    method renamer:
      enabled: false
  custom package: 'false'
  exclusions: []